# Generated by Django 5.1 on 2024-09-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='gpoup_name',
        ),
        migrations.AddField(
            model_name='anime',
            name='title_name',
            field=models.TextField(default=1, verbose_name='Название тайтла'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.TextField(verbose_name='ФИ'),
        ),
    ]
