# Generated by Django 5.1 on 2024-09-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_gpoup_name_anime_title_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
    ]
