# Generated by Django 5.1 on 2024-09-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название студии')),
            ],
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Анимешки'},
        ),
        migrations.RemoveField(
            model_name='anime',
            name='name',
        ),
        migrations.AddField(
            model_name='anime',
            name='date',
            field=models.TextField(default=1, verbose_name='Дата выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='title_name',
            field=models.TextField(verbose_name='Название аниме'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.studio'),
        ),
    ]
