# Generated by Django 5.1 on 2024-10-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_country_director_genre_status_alter_studio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
    ]
