# Generated by Django 5.1 on 2024-11-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='anime.status'),
            preserve_default=False,
        ),
    ]
