# Generated by Django 5.1 on 2024-11-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_anime_picture_country_picture_director_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='anime_pictures/'),
        ),
    ]
